parameters:
  security_headers:
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy
    Cross-Origin-Opener-Policy: same-origin

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy
    Cross-Origin-Resource-Policy: same-origin

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
    Referrer-Policy: strict-origin-when-cross-origin

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
    # Register website on https://hstspreload.org/
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
    X-Content-Type-Options: nosniff

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
    X-Frame-Options: DENY
